"""Initial migration

Revision ID: 010c4c11b379
Revises: 06cd0b32b243
Create Date: 2024-03-19 15:49:00.661200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '010c4c11b379'
down_revision: Union[str, None] = '06cd0b32b243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_posts', sa.Column('update_time', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_posts', 'update_time')
    # ### end Alembic commands ###
