"""Initial migration

Revision ID: 079c2f86b2e3
Revises: 72798697c783
Create Date: 2024-03-19 16:54:20.930560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '079c2f86b2e3'
down_revision: Union[str, None] = '72798697c783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_posts', sa.Column('isDisabledTitle', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_posts', 'isDisabledTitle')
    # ### end Alembic commands ###
