"""empty message

Revision ID: 143e55a33961
Revises: 046ee3d8f82c
Create Date: 2024-03-25 15:06:05.066234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '143e55a33961'
down_revision: Union[str, None] = '046ee3d8f82c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.add_column('email', sa.Column('email_id', sa.String(length=36), nullable=False))
    op.drop_column('signature', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signature', sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('email', 'email_id')
    op.create_table('user',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=11), nullable=False),
    sa.Column('count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('last_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('create_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
