"""Initial migration

Revision ID: 1e7e6c6057cc
Revises: 
Create Date: 2024-01-30 10:07:17.372866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import  tool
# revision identifiers, used by Alembic.
revision: str = '1e7e6c6057cc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id',
               existing_type=sa.BINARY(length=16),
               type_=tool.classDb.UUIDType(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id',
               existing_type=tool.classDb.UUIDType(),
               type_=sa.BINARY(length=16),
               existing_nullable=False)
    # ### end Alembic commands ###
