"""empty message

Revision ID: 309e4102069b
Revises: 631eff4db4aa
Create Date: 2024-03-25 15:45:30.886991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '309e4102069b'
down_revision: Union[str, None] = '631eff4db4aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('copy_email', 'copy_email_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_constraint('copy_email_ibfk_1', 'copy_email', type_='foreignkey')
    op.create_foreign_key(None, 'copy_email', 'email', ['copy_email_id'], ['id'])
    op.drop_column('copy_email', 'email_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copy_email', sa.Column('email_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'copy_email', type_='foreignkey')
    op.create_foreign_key('copy_email_ibfk_1', 'copy_email', 'email', ['email_id'], ['id'])
    op.alter_column('copy_email', 'copy_email_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###
