"""Initial migration

Revision ID: 4eb358969317
Revises: 079c2f86b2e3
Create Date: 2024-03-20 09:02:15.029373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb358969317'
down_revision: Union[str, None] = '079c2f86b2e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_posts', sa.Column('isDeleted', sa.Integer(), nullable=False))
    op.add_column('user_posts', sa.Column('isTop', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_posts', 'isTop')
    op.drop_column('user_posts', 'isDeleted')
    # ### end Alembic commands ###
