"""Initial migration

Revision ID: 72798697c783
Revises: 010c4c11b379
Create Date: 2024-03-19 16:49:41.851432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72798697c783'
down_revision: Union[str, None] = '010c4c11b379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_posts', sa.Column('title', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_posts', 'title')
    # ### end Alembic commands ###
