"""Initial migration

Revision ID: 9cbc2559501f
Revises: f86e6dd658ac
Create Date: 2024-01-30 12:06:07.068127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cbc2559501f'
down_revision: Union[str, None] = 'f86e6dd658ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lottery_records', sa.Column('name', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lottery_records', 'name')
    # ### end Alembic commands ###
