"""Initial migration

Revision ID: aa9aa8f265e0
Revises: aace8c5ad3b8
Create Date: 2024-02-14 13:49:46.643028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa9aa8f265e0'
down_revision: Union[str, None] = 'aace8c5ad3b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dict', sa.Column('status', sa.Integer(), nullable=False))
    op.add_column('dict_child', sa.Column('status', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dict_child', 'status')
    op.drop_column('dict', 'status')
    # ### end Alembic commands ###
