"""empty message

Revision ID: b5e1e57b4681
Revises: f11db24b1077
Create Date: 2024-03-25 15:50:15.269115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5e1e57b4681'
down_revision: Union[str, None] = 'f11db24b1077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('copy_email_ibfk_1', 'copy_email', type_='foreignkey')
    op.create_foreign_key(None, 'copy_email', 'email', ['copy_email_id'], ['email_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'copy_email', type_='foreignkey')
    op.create_foreign_key('copy_email_ibfk_1', 'copy_email', 'email', ['copy_email_id'], ['id'])
    # ### end Alembic commands ###
